server:
  port: 3333
spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #    oss配置
    alicloud:
      access-key: LTAI4G9qTMpZUXiTFFb6NpTc
      secret-key: K8VVKnc6B2
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-i